name: 'Portainer Pull Image Recreate Action'
description: 'This action will pull the latest docker image and then recreate the container'
inputs:
  portainer-url:
    description: 'https://portainer.domain.com'
    required: true
  portainer-api-key:
    description: 'ptr_dQeZ7ljSgcEJ7tQPt+H7d59sNpujkKpD3J/2tGzghGE='
    required: true
  portainer-endpoint-id:
    description: 2
    required: true
  portainer-container-name:
    description: 'my-container-name'
    required: true
  portainer-registry-auth:
    description: 'eyJyZWdpc3RyeUlkIjoxfQ=='
    required: false
runs:
  using: 'node16'
  main: 'index.js'